# Generated by Django 5.0.8 on 2024-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0002_rename_loanapplication_enregistrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ1', models.CharField(max_length=100)),
                ('champ2', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Enregistrement',
        ),
    ]
