# Generated by Django 5.0.8 on 2024-08-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0003_monmodele_delete_enregistrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ1', models.CharField(max_length=100)),
                ('champ2', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MonModele',
        ),
    ]
