# Generated by Django 5.0.8 on 2024-08-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0004_pret_delete_monmodele'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret_banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('adresse_postale', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('numero_securite_sociale', models.CharField(max_length=20)),
                ('montant_pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_pret', models.PositiveIntegerField(help_text='Durée du prêt en mois')),
                ('objectif_pret', models.CharField(choices=[('achat_voiture', 'Achat de voiture'), ('travaux', 'Travaux'), ('etudes', 'Études'), ('autre', 'Autre')], max_length=100)),
                ('revenus_mensuels', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depenses_mensuelles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat_civil', models.CharField(choices=[('marie', 'Marié'), ('celibataire', 'Célibataire'), ('autre', 'Autre')], max_length=20)),
                ('nombre_personnes_charge', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pret',
        ),
    ]
