# Generated by Django 5.0.8 on 2024-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0006_pret_delete_pret_banque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pret',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
    ]
