# Generated by Django 5.0.8 on 2024-08-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0007_alter_pret_nom_alter_pret_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret_banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('montant_pret', models.CharField(max_length=200)),
                ('dure_pret', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pret',
        ),
    ]
