# Generated by Django 5.0.8 on 2024-08-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0008_pret_banque_delete_pret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret_banques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('montant_pret', models.CharField(max_length=200)),
                ('dure_pret', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pret_banque',
        ),
    ]
